app.title=Calories management
app.home=Home
app.footer=Internship <a href="https://github.com/JavaOPs/topjava" target=_blank>Spring 5/JPA Enterprise (Topjava)</a> application
app.login=Login as
user.title=Users
user.name=Name
user.email=Email
user.roles=Roles
user.active=Active
user.registered=Registered
meal.title=Meals
meal.create=Create a meal
meal.edit=Edit the meal
meal.calories=Calories
meal.description=Description
meal.date=Date
meal.datetime=DateTime
meal.from_date_inclusive=From Date (inclusive)
meal.to_date_inclusive=To Date (inclusive)
meal.from_time_inclusive=From Time (inclusive)
meal.to_time_exclusive=To Time (exclusive)
common.select=Select
common.save=Save
common.cancel=Cancel
common.filter=Filter
common.update=Update
common.delete=Delete